# Default configuration for Soroban Graph Stellar Ingester
database:
  url: "${DATABASE_URL}"
  max_open_connections: 25
  max_idle_connections: 10
  connection_max_lifetime: "5m"

stellar:
  network_passphrase: "Test SDF Network ; September 2015"
  history_archive_urls:
    - "https://history.stellar.org/prd/core-testnet/core_testnet_001"
  start_ledger: 0
  end_ledger: 0

server:
  port: 8080
  host: "0.0.0.0"
  gin_mode: "debug"
  enable_websocket: true

logging:
  level: "info"
  format: "json"  # json or text

ingestion:
  batch_size: 1000
  retry_attempts: 3
  retry_delay: "5s"
  enable_captive_core: false

captive_core:
  binary_path: ""
  config_path: ""
  
websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  write_wait: "10s"
  pong_wait: "60s"
  ping_period: "54s"