# Development environment overrides
logging:
  level: "debug"
  format: "text"

server:
  gin_mode: "debug"

database:
  url: "${DATABASE_URL}"
  
ingestion:
  batch_size: 100  # Smaller batches for development