# Testnet environment configuration
logging:
  level: "debug"
  format: "text"

server:
  gin_mode: "debug"

database:
  url: "${DATABASE_URL}"
  
stellar:
  # Contract addresses to filter for (testnet addresses)
  filter_contracts:
    - "CADB73DZ7QP5BG5ZG6MRRL3J3X4WWHBCJ7PMCVZXYG7ZGCPIO2XCDBOM"
    - "CAD6YMZCO4Q3L5XZT2FD3MDHP3ZHFMYL24RZYG4YQAL4XQKVGVXYPSQQ"
  
ingestion:
  batch_size: 100  # Smaller batches for development