# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run go fmt
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Build application
      run: go build -v -o sorobangraph.attest.so .

    - name: Build migration tool
      run: go build -v -o migrate ./cmd/migrate

    - name: Build healthcheck tool  
      run: go build -v -o healthcheck ./cmd/healthcheck

    - name: Test (skip if no tests)
      run: |
        if go list ./... | xargs -n1 go list -f '{{.Dir}} {{.TestGoFiles}}' | grep -v '\[\]' > /dev/null; then
          go test -v ./...
        else
          echo "No tests found, skipping test step"
        fi
